/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PPRD;

import goshredding.data.*;
import goshredding.vo.EventVO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.border.BevelBorder;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author syp386
 */
public class EventCellPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventItemPanel
     */
    private EventVO eventObj;

    public EventCellPanel(EventVO eventVO) {
        initComponents();
        this.eventObj = eventVO;
        eventNameLbl.setText(eventObj.eventName);
        eventDateLbl.setText(eventObj.eventDate);
        timeLbl.setText(eventObj.eventTime);
        if (eventObj.eventPicName != null && eventObj.eventPicName.length() > 0) {

            try {

                Image image = new ImageIcon(getClass().getResource(eventObj.eventPicName)).getImage();
                image = image.getScaledInstance(104, 60, Image.SCALE_SMOOTH);
                imageLbl.setIcon(new ImageIcon(image));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        if (eventObj.eventTypePicName != null && eventObj.eventTypePicName.length() > 0) {

            try {

                Image image2 = new ImageIcon(getClass().getResource(eventObj.eventTypePicName)).getImage();
                image2 = image2.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                eventTypeLbl.setIcon(new ImageIcon(image2));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eventNameLbl = new javax.swing.JLabel();
        eventDateLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        imageLbl = new javax.swing.JLabel();
        eventTypeLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 246, 254));
        setPreferredSize(new java.awt.Dimension(810, 75));

        jPanel1.setBackground(new java.awt.Color(239, 246, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(810, 75));
        jPanel1.setLayout(null);

        eventNameLbl.setFont(new java.awt.Font("Lucida Grande", 0, 19)); // NOI18N
        eventNameLbl.setText("Event name");
        jPanel1.add(eventNameLbl);
        eventNameLbl.setBounds(8, 14, 370, 23);

        eventDateLbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        eventDateLbl.setText("2019/10/30");
        jPanel1.add(eventDateLbl);
        eventDateLbl.setBounds(8, 43, 86, 17);

        timeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        timeLbl.setText("12:00 PM");
        jPanel1.add(timeLbl);
        timeLbl.setBounds(405, 26, 78, 21);
        jPanel1.add(imageLbl);
        imageLbl.setBounds(528, 8, 104, 60);
        jPanel1.add(eventTypeLbl);
        eventTypeLbl.setBounds(690, 13, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventDateLbl;
    private javax.swing.JLabel eventNameLbl;
    private javax.swing.JLabel eventTypeLbl;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel timeLbl;
    // End of variables declaration//GEN-END:variables

}
