/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goshreddingPrototype;

import goshredding.data.EventCellRender;
import goshredding.data.EventTableModel;
import goshredding.data.EventVO;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author huwei
 */
public class MainFormUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private ArrayList eventList = new ArrayList();
    public MainFormUI() {
        initComponents();
        eventTable.setRowHeight(75);
        
        eventTable.getTableHeader().setVisible(false);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setPreferredSize(new Dimension(0, 0));
        eventTable.getTableHeader().setDefaultRenderer(renderer);

        EventVO event1 = new EventVO();
        event1.eventName = "Snow Skating";
        event1.eventDate = "01/02/2019";
        event1.eventTimeRemaining = "03:12;01;57";

        EventVO event2 = new EventVO();
        event2.eventName = "Super bike";
        event2.eventDate = "02/02/2019";
        event2.eventTimeRemaining = "04:02:15:02";

        EventVO event3 = new EventVO();
        event3.eventName = "bikeOlympic";
        event3.eventDate = "02/07/2019";
        event3.eventTimeRemaining = "04:03:01:02";

        EventVO event4 = new EventVO();
        event4.eventName = "Skiing 2020";
        event4.eventDate = "04/02/2019";
        event4.eventTimeRemaining = "06:03:01:02";

        EventVO event5 = new EventVO();
        event5.eventName = "Snow Skating";
        event5.eventDate = "08/02/2019";
        event5.eventTimeRemaining = "10:03:01:02";

        eventList.add(event1);
        eventList.add(event2);
        eventList.add(event3);
        eventList.add(event4);
        eventList.add(event5);

        EventTableModel eventTableModel = new EventTableModel(eventList);
        eventTable.setModel(eventTableModel);
        TableColumnModel tcm = eventTable.getColumnModel();
        TableColumn tc = tcm.getColumn(0);
        tc.setPreferredWidth(200);
        tc.setCellRenderer(new EventCellRender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jPanel = new javax.swing.JPanel();
        greetingTxt = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        notificationBtn = new javax.swing.JButton();
        myEventBtn = new javax.swing.JButton();
        myProfileBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        newGroupBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventTable = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 246, 254));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 480));

        jPanel.setBackground(new java.awt.Color(239, 246, 254));
        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel.setPreferredSize(new java.awt.Dimension(850, 480));
        jPanel.setLayout(null);

        greetingTxt.setText("Good morning, Tony");
        jPanel.add(greetingTxt);
        greetingTxt.setBounds(46, 20, 140, 16);

        dateTxt.setText("dd/mm/yyyy 9:00 AM");
        jPanel.add(dateTxt);
        dateTxt.setBounds(196, 20, 138, 16);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Find your next event");
        jPanel.add(jLabel1);
        jLabel1.setBounds(525, 80, 259, 30);

        jLabel2.setText("Days : hours: minutes : seconds");
        jPanel.add(jLabel2);
        jLabel2.setBounds(206, 80, 230, 16);

        jLabel3.setText("\"Do want you can't\" --- Casey Neistat");
        jPanel.add(jLabel3);
        jLabel3.setBounds(579, 20, 260, 16);

        notificationBtn.setBackground(new java.awt.Color(72, 124, 175));
        notificationBtn.setText("Notification");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });
        jPanel.add(notificationBtn);
        notificationBtn.setBounds(586, 39, 120, 35);

        myEventBtn.setBackground(new java.awt.Color(72, 124, 175));
        myEventBtn.setText("My events");
        myEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myEventBtnActionPerformed(evt);
            }
        });
        jPanel.add(myEventBtn);
        myEventBtn.setBounds(454, 39, 120, 35);

        myProfileBtn.setBackground(new java.awt.Color(72, 124, 175));
        myProfileBtn.setText("My profile");
        myProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileBtnActionPerformed(evt);
            }
        });
        jPanel.add(myProfileBtn);
        myProfileBtn.setBounds(718, 39, 120, 35);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel20.setText("Upcoming events");
        jPanel.add(jLabel20);
        jLabel20.setBounds(50, 50, 220, 30);

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jPanel.add(jTextField1);
        jTextField1.setBounds(454, 116, 293, 35);

        jButton5.setBackground(new java.awt.Color(72, 124, 175));
        jButton5.setText("search");
        jPanel.add(jButton5);
        jButton5.setBounds(753, 117, 91, 35);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel19.setText("You might be interested in...");
        jPanel.add(jLabel19);
        jLabel19.setBounds(460, 160, 259, 19);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(239, 246, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(376, 500));
        jPanel1.setLayout(null);

        jLabel21.setText("24/10/2019");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(0, 120, 78, 16);

        jPanel2.setBackground(new java.awt.Color(239, 246, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel22.setText("Clyne MTB");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(6, 6, 81, 20);

        jLabel23.setText("Mountain biking");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(7, 30, 103, 16);

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel24.setText("4:00 PM");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(270, 10, 80, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 20, 370, 50);

        jPanel9.setBackground(new java.awt.Color(239, 246, 254));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel25.setText("Clyne MTB");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(6, 6, 81, 20);

        jLabel26.setText("Mountain biking");
        jPanel9.add(jLabel26);
        jLabel26.setBounds(7, 30, 103, 16);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel27.setText("4:00 PM");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(270, 10, 80, 21);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 68, 370, 50);

        jLabel28.setText("24/10/2019");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(0, 0, 78, 16);

        jPanel10.setBackground(new java.awt.Color(239, 246, 254));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel29.setText("Clyne MTB");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(6, 6, 81, 20);

        jLabel30.setText("Mountain biking");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(7, 30, 103, 16);

        jLabel31.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel31.setText("4:00 PM");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(270, 10, 80, 21);

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 140, 370, 50);

        jPanel11.setBackground(new java.awt.Color(239, 246, 254));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel32.setText("Clyne MTB");
        jPanel11.add(jLabel32);
        jLabel32.setBounds(6, 6, 81, 20);

        jLabel33.setText("Mountain biking");
        jPanel11.add(jLabel33);
        jLabel33.setBounds(7, 30, 103, 16);

        jLabel34.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel34.setText("4:00 PM");
        jPanel11.add(jLabel34);
        jLabel34.setBounds(270, 10, 80, 21);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 188, 370, 50);

        jScrollPane2.setViewportView(jPanel1);

        jPanel.add(jScrollPane2);
        jScrollPane2.setBounds(460, 190, 380, 230);

        newGroupBtn.setBackground(new java.awt.Color(72, 124, 175));
        newGroupBtn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        newGroupBtn.setText("Start a new group");
        newGroupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupBtnActionPerformed(evt);
            }
        });
        jPanel.add(newGroupBtn);
        newGroupBtn.setBounds(460, 430, 380, 40);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All events", "mountain biking", "skateboarding", "snowboarding", "sort by popularity", "sort by time" }));
        jPanel.add(jComboBox1);
        jComboBox1.setBounds(710, 160, 130, 27);

        eventTable.setBackground(new java.awt.Color(239, 246, 254));
        eventTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eventTable.setGridColor(new java.awt.Color(0, 0, 0));
        eventTable.setIntercellSpacing(new java.awt.Dimension(0, 2));
        eventTable.setShowGrid(false);
        jScrollPane3.setViewportView(eventTable);

        jPanel.add(jScrollPane3);
        jScrollPane3.setBounds(20, 110, 411, 356);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void myEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myEventBtnActionPerformed
        MyEventsUI myFrm = new MyEventsUI();
        myFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myEventBtnActionPerformed

    private void newGroupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupBtnActionPerformed
        EventInformationUI eiFrm = new EventInformationUI();
        eiFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newGroupBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
        NotificationCentreUI ncFrm = new NotificationCentreUI();
        ncFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_notificationBtnActionPerformed

    private void myProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileBtnActionPerformed
        myProfileUI mpFrm = new myProfileUI();
        mpFrm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_myProfileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try{
            UIManager.setLookAndFeel("com.jtatto.plaf.aluminium.AluminiumLookAndFeel");
        }catch(Exception ee){
            
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateTxt;
    private javax.swing.JTable eventTable;
    private javax.swing.JLabel greetingTxt;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton myEventBtn;
    private javax.swing.JButton myProfileBtn;
    private javax.swing.JButton newGroupBtn;
    private javax.swing.JButton notificationBtn;
    // End of variables declaration//GEN-END:variables
}
